const INCREMENT = "INCREMENT";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const SET_AGE = "SET_AGE";
const GET_TEXTBOOKS = "GET_TEXTBOOKS";
const HANDLE_SEARCH = "HANDLE_SEARCH";
const SEARCH_AND_UPDATE_TEXTBOOKS = "SEARCH_AND_UPDATE_TEXTBOOKS";
const GET_CART_ITEMS = "GET_CART_ITEMS";
const ADD_TO_CART = "ADD_TO_CART";
const LOGIN_WITH_OLD_AUTH_TOKEN = "LOGIN_WITH_OLD_AUTH_TOKEN";
const CREATE_NEW_TEXTBOOK = "CREATE_NEW_TEXTBOOK";
const SIGNUP = "SIGNUP";
// const FETCH_TEXTBOOKS_PENDING = "FETCH_TEXTBOOKS_PENDING";
// const FETCH_TEXTBOOKS_SUCCESS = "FETCH_TEXTBOOKS_SUCCESS";
// const FETCH_TEXTBOOKS_ERROR = "FETCH_TEXTBOOKS_ERROR";

export {
  INCREMENT,
  LOGIN,
  SET_AGE,
  GET_TEXTBOOKS,
  HANDLE_SEARCH,
  SEARCH_AND_UPDATE_TEXTBOOKS,
  LOGOUT,
  GET_CART_ITEMS,
  ADD_TO_CART,
  LOGIN_WITH_OLD_AUTH_TOKEN,
  CREATE_NEW_TEXTBOOK,
  SIGNUP
};



