const INCREMENT = "INCREMENT";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const SET_AGE = "SET_AGE";
const GET_TEXTBOOKS = "GET_TEXTBOOKS";
const UPDATE_SEARCH = "UPDATE_SEARCH";
const SEARCH_AND_UPDATE_TEXTBOOKS = "SEARCH_AND_UPDATE_TEXTBOOKS";
const GET_CART_ITEMS = "GET_CART_ITEMS";
const ADD_TO_CART = "ADD_TO_CART";
const LOGIN_WITH_OLD_AUTH_TOKEN = "LOGIN_WITH_OLD_AUTH_TOKEN";
const CREATE_NEW_TEXTBOOK = "CREATE_NEW_TEXTBOOK";
const SIGNUP = "SIGNUP";
const UPDATE_FILTERS = "UPDATE_FILTERS";
const DELETE_FROM_CART = "DELETE_FROM_CART";
const GET_USER_PUBLIC_INFO = "GET_USER_PUBLIC_INFO";
const UPDATE_SETTINGS = "UPDATE_SETTINGS";
const GET_SIGNED_IN_PROFILE = "GET_SIGNED_IN_PROFILE";

// const FETCH_TEXTBOOKS_PENDING = "FETCH_TEXTBOOKS_PENDING";
// const FETCH_TEXTBOOKS_SUCCESS = "FETCH_TEXTBOOKS_SUCCESS";
// const FETCH_TEXTBOOKS_ERROR = "FETCH_TEXTBOOKS_ERROR";

export {
  INCREMENT,
  LOGIN,
  SET_AGE,
  GET_TEXTBOOKS,
  UPDATE_SEARCH,
  SEARCH_AND_UPDATE_TEXTBOOKS,
  LOGOUT,
  GET_CART_ITEMS,
  ADD_TO_CART,
  LOGIN_WITH_OLD_AUTH_TOKEN,
  CREATE_NEW_TEXTBOOK,
  SIGNUP,
  UPDATE_FILTERS,
  DELETE_FROM_CART,
  GET_USER_PUBLIC_INFO,
  UPDATE_SETTINGS,
  GET_SIGNED_IN_PROFILE
};



