const INCREMENT = "INCREMENT";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const SET_AGE = "SET_AGE";
const GET_TEXTBOOKS = "GET_TEXTBOOKS";
const HANDLE_SEARCH = "HANDLE_SEARCH";
const SEARCH_AND_UPDATE_TEXTBOOKS = "SEARCH_AND_UPDATE_TEXTBOOKS";
// const FETCH_TEXTBOOKS_PENDING = "FETCH_TEXTBOOKS_PENDING";
// const FETCH_TEXTBOOKS_SUCCESS = "FETCH_TEXTBOOKS_SUCCESS";
// const FETCH_TEXTBOOKS_ERROR = "FETCH_TEXTBOOKS_ERROR";

export {
  INCREMENT,
  LOGIN,
  SET_AGE,
  GET_TEXTBOOKS,
  HANDLE_SEARCH,
  SEARCH_AND_UPDATE_TEXTBOOKS,
  LOGOUT
};



